### PR TITLE
retain

### PR DESCRIPTION
**Pull request by ghazel**
#282

### CODE REVIEW

**Comment by kattrali** [comment]
Thanks, @ghazel! Out of curiosity, what version of Xcode are you running?

**Comment by ghazel** [comment]
Xcode Version 9.4 (9F1027a)

**Comment by ghazel** [comment]
You should be able to trigger it with `-Wall -Werror` on just about any version, though.

**Comment by kattrali** [comment]
Right - we have `-Werror` on already though, I'm not sure why that didn't trigger it.

**Comment by ghazel** [comment]
Ah, it's triggered by `-Wextra` (which includes this specific warning, `-Wobjc-property-no-attribute`). The reason I see it and you don't is that my iOS app defines `-Wextra`, and by including `Bugsnag.h` in my project (which includes `BugsnagConfiguration.h`), the compiler uses my warning flags on your code.

I tried defining `-Wextra` in the Bugsnag project, and that raises a whole bunch of (easily fixed) errors. So that's up to y'all.

Thankfully, this PR seems to cover all the public-facing cases.

**Comment by NSExceptional** [comment]
Unrelated to this project, but I can't seem to trigger this warning at all in Xcode itself, even with `-Weverything`

**Pull request merged**
