### PR TITLE
Import Bugsnag headers before reading preprocessor defines

### PR DESCRIPTION
**Pull request by bolsinga**
Summary:
- This change is a little different than https://github.com/bugsnag/bugsnag-react-native/pull/455 in that it just has .m files import their header files first thing.
- Also do not query `TARGET_OS_MAC` first as that is true for `TARGET_IOS_SIMULATOR`.

Test Plan:
- Debugging in Bugsnag for this code.
- I added a compiler error in every `TARGET_OS_IPHONE` conditional and ensured that they all worked. This is how I found the ones found in this diff.

## Goal

Fix building Bugsnag via Bazel

## Design

Ensure class headers are imported first, which brings in Foundation, which brings in TargetConditionals.h. This is typical code structure.

## Changeset

Change the imports of files so that preprocessor macros are defined when read.

## Tests

I added nonsense characters, to ensure that before the change would show that code wrapped in macro was not compiling, and that after the change it was. At runtime I was able to step into the `BSGOutOfMemoryWatchdog` which is usually preprocessor wrapped with `BSGOOMAvailable`, and it wasn't compiling for us.

### Outstanding Questions

- This pull request is ready for:
  - [ ] Initial review of the intended approach, not yet feature complete
  - [ ] Structural review of the classes, functions, and properties modified
  - [x] Final review
  - [ ] Release

- [x] The correct target branch has been selected (`master` for fixes, `next` for
  features)
- [ ] If this is intended for release have all of the [pre-release checks](CONTRIBUTING.md) been considered?
- [ ] Consistency across platforms for structures or concepts added or modified
- [ ] Consistency between the changeset and the goal stated above
- [ ] Internal consistency with the rest of the library - is there any overlap between existing interfaces and any which have been added?
- [ ] Usage friction - is the proposed change in usage cumbersome or complicated?
- [ ] Performance and complexity - are there any cases of unexpected O(n^3) when iterating, recursing, flat mapping, etc?
- [ ] Concurrency concerns - if components are accessed asynchronously, what issues will arise
- [ ] Thoroughness of added tests and any missing edge cases
- [ ] Idiomatic use of the language

### CODE REVIEW

**Comment by jerrymarino** [comment]
@bolsinga  I didn't see how this code would work in Xcode but not Bazel. As far as I can tell, this is broken for all bugsnag users. Would you mind clarifying so we can make sure to isolate any other issues related to this? We should 100% support building bugsnag with PodToBUILD and Bazel.

Anyhow, I submitted bugsnag/bugsnag-react-native#455 I don't have a strong preference on how what the actual fix is.

**Comment by bolsinga** [comment]
AFAIK it works because somehow the code must be seeing the macros defined when it has been tested and used by others. We know others successfully see OOM reports from Bugsnag. Our build system exposed this issue. However I do not think it is solely a build system issue nor a code issue. I think the combination of the two shows these files are not importing their own headers first. When they do this they automatically get Foundation and TargetConditionals.

I think this fix is simple and it is atypical to manually import TargetConditionals.

**Comment by mattdyoung** [comment]
@jerrymarino @bolsinga 
I can see you've both been discussing these build problems, both on this PR and on https://github.com/bugsnag/bugsnag-react-native/pull/455.

Are these both aiming to solve the same problem or are both required? What ultimately are these issues blocking you from achieving and is this an issue for bugsnag-cocoa or bugsnag-react-native or both?

**Comment by bolsinga** [comment]
> @jerrymarino @bolsinga
> I can see you've both been discussing these build problems, both on this PR and on [bugsnag/bugsnag-react-native#455](https://github.com/bugsnag/bugsnag-react-native/pull/455).
> 
> Are these both aiming to solve the same problem or are both required? What ultimately are these issues blocking you from achieving and is this an issue for bugsnag-cocoa or bugsnag-react-native or both?

We are both aiming to solve the same problem.

We import bugsnag-react-native into our application. As you know, bugsnag-cocoa is a dependency. So we need the fix in both, but it probably ought to apply here.

We use https://github.com/pinterest/PodToBUILD to bring Bugsnag-React-Native into our application which builds with Bazel. Under these circumstances, it is true that the TARGET_OS_IPHONE macro is not defined when the OOM watchdog is going to define BSGOOMAvailable macro. This fix just has the .m files import their .h files first thing, and everything works out. Thanks.

**Comment by mattdyoung** [comment]
@bolsinga - thanks! We're taking a look at both PRs and will decide on the best way forward.

**Comment by jerrymarino** [comment]
Ah ok cool, I just wanted to confirm that this bug wasn't related to PodToBUILD or using Bazel 👍

**Comment by mattdyoung** [comment]
Hi @jerrymarino @bolsinga 
Yes, the macros we're using look to be incorrect in some cases and we'd like to investigate fully.

We're just working towards a new major release of bugsnag-cocoa in the coming weeks, so will be looking to resolve this as part of that work. If you need the fix in the short term I'd suggest using a fork with this PR.

**Comment by bolsinga** [comment]
Thanks for the update. We currently have a local workaround and look forward to the real fix. 

Would you be able to verify if the oom watchdog builds for other iOS clients?

**Comment by johnkiely1** [comment]
Hi @bolsinga,

Im not sure I understand what you mean by your question
> Would you be able to verify if the oom watchdog builds for other iOS clients?
Could you explain further on this please?

**Comment by bolsinga** [comment]
Sure. For the way we build this code, the OOM watch dog code wasn’t compiling due to it referencing the OS macros prior to the source importing a header that defines these macros first. 

I assume that this code builds and works for other iOS clients. I haven’t personally confirmed this. My question was basically to confirm that bugsnag does get oom reports from other client code, and thus we’d know that the build issue we see here is unique to our situation.

**Comment by johnkiely1** [comment]
Thanks for clarifying that. Yes you assume correctly, it builds and works fine for other iOS clients.

**Comment by bolsinga** [comment]
Thanks! Our current workaround in our build system is to explicitly import TargetConditionals.h for every BugSnag file. 

That workaround is not necessary with this PR applied. 

I think this PR is a simple logical cleanup, but our workaround will hold up until this PR lands. 

Thanks again for your time and understanding.

**Comment by mattdyoung** [comment]
We believe this issue has now been fixed in https://github.com/bugsnag/bugsnag-cocoa/pull/654, released in [v6.0.0](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.0.0).

Note: There are a number of breaking changes in v6.0.0 as part of an effort to improve the interface and make it more consistent across our error reporting libraries, so please refer to the upgrade guide:
https://github.com/bugsnag/bugsnag-cocoa/blob/master/UPGRADING.md

**Pull request closed without merging**
