### PR TITLE
Thread safety fixes

### PR DESCRIPTION
**Pull request by fractalwrench**
Adds locks for methods which could crash, and makes public API properties atomic. Crashes in the library can be reproduced by using the following approach:

```
for (int k = 0; k < 10000; k++) {
    NSLog(@"Attempt: %d", k);
    [Bugsnag leaveBreadcrumbWithMessage:@"generate non-fatal exception"];
    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
        NSError *error = [NSError errorWithDomain:@"thread test" code:0 userInfo:nil];
        [Bugsnag notifyError:error];
    });
}
```

### CODE REVIEW

**Comment by fractalwrench** [comment]
This should address the following issues:

https://github.com/bugsnag/bugsnag-cocoa/issues/199
https://github.com/bugsnag/bugsnag-react-native/issues/174

**Comment by sberrevoets** [comment]
On Xcode 9.1 we're seeing a number of warnings related to this change:

`Writable atomic property 'capacity' cannot pair a synthesized getter with a user defined setter. Setter and getter must both be synthesized, or both be user defined,or the property must be nonatomic.`

There are 5 other properties this applies to as well.

**Comment by kattrali** [comment]
@sberrevoets I've got a fix for this in https://github.com/bugsnag/bugsnag-cocoa/commit/7670931aa056227ffcc1caa96c60e3a52f1360ed, also turned on warnings as errors.

**Comment by sberrevoets** [comment]
Awesome, thanks! 🙏

**Pull request merged**
