### PR TITLE
[PLAT-9816] Improved reliability of obtaining memory metadata on iOS 13+

### PR DESCRIPTION
**Pull request by robert-smartbear**
## Goal

Improved reliability of obtaining memory metadata on iOS 13+

## Testing

E2E Tests

### CODE REVIEW

**Comment by twometresteve** [comment]
Did you see the warning about BSGRunContext.h above?

**Comment by robert-smartbear** [comment]
> Can you confirm that the e2e tests pass on a device in the range iOS 15.0-15.3 on BitBar? Just a brief comment in the PR description is fine, I don’t need hard proof. I’ve set up some extra device groups, so you can use of the groups from `--device=IOS_15_0` to `--device=IOS_15_3` for that (choosing just one of them is fine I think).

Here is a link to a Bitbar test results for 15.1. It used to fail previously: https://cloud.bitbar.com/#testing/projects/207188123/209297604

**Comment by robert-smartbear** [comment]
> Did you see the warning about BSGRunContext.h above?

I fixed the issue

**Review by kstenerud — APPROVED** [review]

**Review by twometresteve — APPROVED** [review]
Approved from a test perspective.  I can't see the BitBar link you posted, but I take your word for it.

**Pull request merged**
